name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  gcc:
    strategy:
      matrix:
        version: [8, 9, 10, 11]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install GCC ${{ matrix.version }}
        run: sudo apt-get install -y gcc-${{ matrix.version }} g++-${{ matrix.version }}

      - name: Configure tests
        env:
          CXX: g++-${{ matrix.version }}
        run: cmake -S . -B build
          -D CMAKE_BUILD_TYPE:STRING=Release
          -D ANY_LITE_OPT_SELECT_NONSTD=ON
          -D ANY_LITE_OPT_BUILD_TESTS=ON
          -D ANY_LITE_OPT_BUILD_EXAMPLES=OFF

      - name: Build tests
        run: cmake --build build -j 4

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure -j 4
